# Generated by Django 3.0.3 on 2020-11-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_resd',
            new_name='is_read',
        ),
    ]
