# Generated by Django 3.0.3 on 2020-11-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_post_coupon_state'),
        ('Notification', '0002_auto_20201109_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='blog.Post'),
        ),
    ]
