# Generated by Django 3.0.3 on 2020-03-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories.jpg', upload_to='Categories_pics'),
        ),
    ]
