# Generated by Django 3.0.3 on 2020-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200304_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post_points', models.IntegerField()),
                ('new_comment_points', models.IntegerField()),
                ('new_like_points', models.IntegerField()),
                ('new_favourite_points', models.IntegerField()),
            ],
        ),
    ]
