# Generated by Django 3.0.3 on 2020-04-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200407_0159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
