# Generated by Django 3.0.3 on 2020-04-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_post_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-post_publish',)},
        ),
    ]
