# Generated by Django 3.0.3 on 2020-04-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200420_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
