# Generated by Django 3.0.3 on 2020-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200420_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='post_default', upload_to='images'),
        ),
    ]
