# Generated by Django 3.0.3 on 2020-05-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
