# Generated by Django 3.0.3 on 2020-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200908_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_av_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
