# Generated by Django 3.0.3 on 2020-09-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_comment_comment_av_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_av_rating',
            field=models.FloatField(null=True),
        ),
    ]
