# Generated by Django 3.0.3 on 2020-09-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200908_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_av_rating',
        ),
    ]
