# Generated by Django 3.0.3 on 2020-09-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_comment_comment_av_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rating01',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating02',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating03',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating04',
        ),
    ]
