# Generated by Django 3.1.1 on 2020-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_userip_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userip',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='userip',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
