# Generated by Django 3.0.3 on 2020-09-29 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0045_auto_20200925_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[(None, 'Select coupon type'), ('P', 'Percentage based-coupon'), ('A', 'Amount based-coupon')], default='P', max_length=1, verbose_name='Coupon Type')),
                ('discount', models.DecimalField(decimal_places=2, help_text='Provide percentage value e.g 20 for percentage-based coupon             or amount e.g 2400 for amount-based coupon', max_digits=9)),
                ('usage', models.IntegerField(blank=True, help_text='Provide the number this coupon can be used or leave             this field empty for unlimited usage', null=True, verbose_name='Coupon Usage(optional)')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Activation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'db_table': 'coupons',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False, editable=False, verbose_name='Order Completion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Coupon')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'coupon_orders',
                'ordering': ('-created_at',),
            },
        ),
    ]
