# Generated by Django 3.0.3 on 2020-10-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_coupon_couponorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userip',
            name='post',
        ),
        migrations.AddField(
            model_name='userip',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipp_post', to='blog.Post'),
        ),
    ]
