# Generated by Django 3.0.3 on 2020-10-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
