# Generated by Django 3.0.3 on 2020-10-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_remove_order_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
    ]
