# Generated by Django 3.0.3 on 2020-10-25 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20201017_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userip',
            name='post',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='favpost',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='person',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_update',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='UserIP',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
