# Generated by Django 3.0.3 on 2020-11-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20201107_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coupon_state',
            field=models.BooleanField(default=False),
        ),
    ]
