# Generated by Django 3.0.3 on 2020-11-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_post_coupon_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coupon_state',
        ),
    ]
