# Generated by Django 3.0.3 on 2020-11-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_post_coupon_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Acepted', 'Acepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
