# Generated by Django 3.0.3 on 2020-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_deliver',
            field=models.IntegerField(default=3),
        ),
    ]
