# Generated by Django 3.0.3 on 2020-11-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_post_time_to_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_date_to_deliver',
            field=models.DateTimeField(null=True),
        ),
    ]
