# Generated by Django 3.0.3 on 2020-11-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0077_order_final_date_to_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coupon_state',
        ),
    ]
