# Generated by Django 3.0.3 on 2020-11-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_remove_post_coupon_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(default=5),
        ),
    ]
