# Generated by Django 3.0.3 on 2020-09-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='gender',
        ),
    ]
