# Generated by Django 3.0.3 on 2020-09-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200929_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='taxes',
        ),
    ]
